# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.6
  setup_py_install: true
  use_system_site_packages: true